name: First time setup

on:
  create:

permissions: 
  actions: write
  checks: write
  contents: write

jobs:
  first-time-setup:
    # Ensure this job does not run on the template repository or when the repository is forked
    if: ${{ !github.event.repository.is_template && !github.event.repository.fork }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Execute the first-time-setup script
        run: CI=true JURISDICTION_NAME="$(echo ${{ github.event.repository.name }} | sed 's/openfisca-//')" REPOSITORY_URL="${{ github.repositoryUrl }}" ./first-time-setup.sh

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Adapt template automatically"
          tagging_message: "0.0.1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
